
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-postgres
  template:
    metadata:
      labels:
        app: supabase-postgres
    spec:
      containers:
        - name: postgres
          image: supabase/postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "your_password"
            - name: POSTGRES_USER
              value: "your_user"
            - name: POSTGRES_DB
              value: "your_database"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: supabase-postgres-pvc
